name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.x'

defaults:
  run:
    working-directory: app/backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run lint
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run tests
        run: pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t backend-app .
